-- Supabase Database Schema for HopeXavier First Academy

-- Applications Table
CREATE TABLE IF NOT EXISTS applications (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    parent_full_name TEXT NOT NULL,
    student_full_name TEXT NOT NULL,
    student_type TEXT NOT NULL CHECK (student_type IN ('New', 'Old')),
    phone TEXT NOT NULL,
    email TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Accepted', 'Rejected')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Students Table
CREATE TABLE IF NOT EXISTS students (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    surname TEXT NOT NULL,
    other_names TEXT NOT NULL,
    date_of_birth TEXT NOT NULL,
    gender TEXT NOT NULL,
    class TEXT NOT NULL,
    admission_number TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Staff Table
CREATE TABLE IF NOT EXISTS staff (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    surname TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    gender TEXT NOT NULL,
    email_address TEXT NOT NULL UNIQUE,
    home_address TEXT NOT NULL,
    qualification TEXT NOT NULL,
    state TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- News & Blog Table
CREATE TABLE IF NOT EXISTS news_blog (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    author TEXT NOT NULL,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Exams & Records Table
CREATE TABLE IF NOT EXISTS exams_records (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    term TEXT NOT NULL,
    academic_year TEXT NOT NULL,
    assignment NUMERIC NOT NULL DEFAULT 0,
    first_ca NUMERIC NOT NULL DEFAULT 0,
    second_ca NUMERIC NOT NULL DEFAULT 0,
    mid_term NUMERIC NOT NULL DEFAULT 0,
    exam NUMERIC NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Admin Users Table
CREATE TABLE IF NOT EXISTS admin_users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert default admin user
INSERT INTO admin_users (username, password) 
VALUES ('admin', 'admin123')
ON CONFLICT (username) DO NOTHING;

-- Row Level Security (RLS) setup (Optional, for added security if needed)
-- ALTER TABLE applications ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE students ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE staff ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE news_blog ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE exams_records ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;

-- Create policies to allow read and write access (You may want to restrict this in production)
-- CREATE POLICY "Allow all operations for authenticated users" ON applications FOR ALL USING (true);
-- CREATE POLICY "Allow all operations for authenticated users" ON students FOR ALL USING (true);
-- CREATE POLICY "Allow all operations for authenticated users" ON staff FOR ALL USING (true);
-- CREATE POLICY "Allow all operations for authenticated users" ON news_blog FOR ALL USING (true);
-- CREATE POLICY "Allow all operations for authenticated users" ON exams_records FOR ALL USING (true);
-- CREATE POLICY "Allow all operations for authenticated users" ON admin_users FOR ALL USING (true);
